name: docker build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest image
        run: docker pull kahliloppenheimer/venmo-to-lunch-money:latest
      - name: Build
        run: docker build --tag=kahliloppenheimer/venmo-to-lunch-money:latest .
      - name: Publish
        run: |
          docker login --username=kahliloppenheimer --password-stdin <<< "${{ secrets.DOCKER_HUB_TOKEN }}"
          docker push kahliloppenheimer/venmo-to-lunch-money:latest
